version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
  moviehouse.service:
    build:
      context: ./
      dockerfile: moviehouse.Dockerfile
    container_name: movieHouseService
    restart: always
    ports:
      - "9990:8080"
    depends_on:
      - mongo
      - rabbitmq
  movie.service:
    build:
      context: ./
      dockerfile: movie.Dockerfile
    container_name: movieService
    restart: always
    ports:
      - "9991:8080"
    depends_on:
      - mongo
      - rabbitmq